using System.ComponentModel.DataAnnotations;

namespace TaskManager.API.Models;

/// <summary>
/// Represents a pause request for a task — used when workload escalation
/// triggers an approval flow instead of direct pause.
/// </summary>
public class PauseRequest
{
    [Key]
    public int Id { get; set; }

    public int TaskId { get; set; }
    public TaskItem Task { get; set; } = null!;

    /// <summary>Employee whose task is being requested to pause</summary>
    public int EmployeeId { get; set; }
    public User Employee { get; set; } = null!;

    /// <summary>Who requested the pause (typically the system or TeamLead)</summary>
    public int RequestedByUserId { get; set; }
    public User RequestedBy { get; set; } = null!;

    [MaxLength(500)]
    public string? Reason { get; set; }

    /// <summary>0 = Pending, 1 = Approved, 2 = Rejected</summary>
    public int Status { get; set; } = 0;

    /// <summary>True if generated by workload escalation system, false if manual</summary>
    public bool IsSystemGenerated { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public int? ApprovedByUserId { get; set; }
    public User? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }
}
